name: C/C++ CI

on:
  push:
    branches: [ master, cpp ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      run: cmake .
    - name: make
      run: cmake --build .
    - name: make check
      run: ./bin/unittest
